import "./globals.css";
import { Inter, Gowun_Dodum } from "next/font/google";
import { Navbar, LeftNav, RightNav, IconText, MainLogo, Container } from "./styled";
import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/registry";
import sideLogo from "../public/sideLogo.png";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
export const GowunDodum = Gowun_Dodum({ preload: false,weight:'400' });

export const metadata: Metadata = {
  title: "NTLR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Navbar>
            <LeftNav>
              <Link href="/">
                <Image src={sideLogo} alt=""></Image>
              </Link>
            </LeftNav>
            <RightNav>
              <Link href="/album" style={{ textDecoration: "none" }}>
                <IconText>Album</IconText>
              </Link>

              <Link href="/magazine" style={{ textDecoration: "none" }}>
                <IconText>Magazine</IconText>
              </Link>

              <IconText>Coming soon...</IconText>
              <IconText>Log In</IconText>
            </RightNav>
          </Navbar>
          <Container>{children}</Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
